#! /bin/sh

# # # # # # # #
#  AUTOSTART  #
# # # # # # # #

pgrep -x sxhkd > /dev/null || sxhkd &

#pipewire &
#pipewire-pulse &
#pipewire-media-session &
xsetroot -solid "#2C2E3D"
xsetroot -cursor_name left_ptr &
#xinput --set-prop 11 322 1
sh ~/.config/polybar/polybar.sh &
sxhkd &
#picom -b &
setxkbmap -layout us -option grp:rctrl_rshift_toggle &
nitrogen --restore &
dbus-launch dunst --config ~/.config/dunst/dunstrc &
lxpolkit &
#nm-applet &
xss-lock -l ~/.scripts/transfer-sleep-lock-i3lock.sh &
powerprofilesctl set power-saver &

# # # # # #
#  BSPWM  #
# # # # # #

bspc monitor -d 1 2 3 4 5 6 7 8 9 10
bspc config border_width          2 
bspc config normal_border_color "#3A3F4B"
bspc config active_border_color "#D19A66"
bspc config focused_border_color "#61AFEF"
bspc config presel_feedback_color "#E05355"
bspc config window_gap            10
bspc config split_ratio           0.5
bspc config borderless_monocle    true
bspc config single_monocle        true # smart-gaps 
bspc config gapless_monocle       true
bspc config focus_follows_pointer true

# rules
bspc rule -a gnome-calculator state=floating border=off
bspc rule -a Nitrogen state=floating
bspc rule -a firefox:Toolkit state=floating
bspc rule -a Firefox-esr:Toolkit state=floating
bspc rule -a Gcolor3 state=floating
bspc rule -a xdg-desktop-portal-gnome state=floating
bspc rule -a xdg-desktop-portal-gtk state=floating
bspc rule -a mpv state=fullscreen desktop="^10" follow=on focus=on
bspc rule -a firefox desktop="^2" follow=on focus=on
bspc rule -a Xfce4-terminal desktop="^1" follow=on focus=on
bspc rule -a VSCodium desktop="3" follow=on focus=on
bspc rule -a "spotify" desktop="9" follow=on focus=on
